swagger: "2.0"
info:
  title: Surname API
  description: API for retrieving information about surnames
  version: "1.0"
paths:
  /:
    get:
      summary: Welcome endpoint
      description: Returns a welcome message
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              info:
                type: string
      tags:
        - Welcome
  /surname:
    post:
      summary: Retrieve surname information
      description: Retrieves information about a surname based on gender and surname
      parameters:
        - name: body
          in: body
          description: Request body
          required: true
          schema:
            type: object
            properties:
              gender:
                type: string
              surname:
                type: string
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              result:
                type: string
        "400":
          description: Bad request
        "500":
          description: Internal server error
      tags:
        - Surname
