name: Functional Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  function_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install pytest and mypy
        run: | 
          pip install pytest==7.1.1
          pip install requests
      
      - name: Build and run Docker
        run: |
          docker build -t surname_counter_api -f ./docker/Dockerfile . 
          docker run -p 5000:5000 -d surname_counter_api

      - name: Run function tests
        run: |
          pytest ./tests/function_test.py
